version: '3'
services:
  web:
    build:
      context: ./SDS  # This should be the path to the directory containing your Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
