# Generated by Django 5.0.6 on 2024-08-22 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_student_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course'),
        ),
    ]
